### PR TITLE
Update history

### LINKED ISSUE #557: Update "Flatpak History"
Latest "Flatpak History" item on the [About page](https://flatpak.org/about/) seems to be from 2019. I think it could be a good idea to update it. :-)

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Closes https://github.com/flatpak/flatpak.github.io/issues/557

### CODE REVIEW

**Comment by sonnyp** [comment]
>  GNOME adopting Flatpak
> GNOME Nightly announcement

Thanks for taking over! About GNOME the reason I didn't put it in the list is that Flatpak and GNOME are so intertwined it's not easy to find a specific related milestone.

Given GNOME is already mentioned at the beginning of the list I think it's fine as is

**Comment by TheEvilSkeleton** [comment]
Got it, thanks

**Comment by lionirdeadman** [comment]
While Discord is verified, I would probably wait until they get their hands in the code.. I personally would not feel comfortable with putting that in.

**Comment by alatiera** [comment]
For the record, the gnome-nightly repo has been around *at least* 2016, based on the [setup repo](https://github.com/flatpak/flatpak-build-scripts/) and the refs (3.18/3.20) I had found while poking at it. But I am not sure if we had an earlier version of it as well.

In general it's more of a case Flatpak being developed for and with GNOME rather than "adopting it"

**Comment by TheEvilSkeleton** [comment]
> While Discord is verified, I would probably wait until they get their hands in the code.. I personally would not feel comfortable with putting that in.

I'm fine with dropping it, but I'd like to know others' opinions on it

**Comment by AsciiWolf** [comment]
Is this ready to be merged or should the part about Discord be dropped?

**Comment by AsciiWolf** [comment]
@TheEvilSkeleton Any update about this update? :) Is this ready to be merged?

**Comment by TheEvilSkeleton** [comment]
I think everything is fine

**Pull request merged**
