### PR TITLE
Add Ataraxia Linux

### PR DESCRIPTION
**Pull request by protonesso**
Signed-off-by: Ishimoto Shinobu <nagakamira@gmail.com>

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Is the installation of Flatpak apps using GUI available?

**Comment by protonesso** [comment]
GNOME software is available, yes

2020年5月5日(火) 0:28 AsciiWolf <notifications@github.com>:

**Comment by protonesso** [comment]
Progress?

**Comment by AsciiWolf** [comment]
LGTM, but I will probably wait for someone else to check and merge this.

**Pull request merged**
