### PR TITLE
Reword ubuntu setup instructions

### PR DESCRIPTION
**Pull request by razzeee**
Done by @cassidyjames

### CODE REVIEW

**Comment by razzeee** [comment]
Also added the rewording of the 2nd step, not that happy with the last sentence, but meh

**Comment by cassidyjames** [comment]
Yeah, trying to explain Ubuntu decisions across different versions was complex, but I felt like we needed to try to so people don't get tripped up at least.

**Comment by razzeee** [comment]
This should be good to merge

**Review by AsciiWolf — APPROVED** [review]

**Comment by AsciiWolf** [comment]
Looks good, thanks!

**Comment by AsciiWolf** [comment]
By the way, this has been 1000th commit in this repo. Congratulations! :-)

**Pull request merged**
