### PR TITLE
Alternative dark icons

### PR DESCRIPTION
**Pull request by razzeee**
The elementary icon is still a placeholder and more to show that it works. I've reached out on twitter, asking, which logo they would like to use on a black background. Will amend that change.

### CODE REVIEW

**Comment by mwleeds** [comment]
Whatever we do for Elementary would make sense to do for PureOS, Pisi, and Ataraxia right? On the other hand Mageia and EndeavorOS also don't look great, which might be a reason to look at putting a non-transparent color behind them.

**Comment by razzeee** [comment]
Yes, but primary goal should be to have this mechanism. All those changes should not block the MR as they might take an arbitrary amout of time. Not sure how to contact most of those distros and I had a quick look at google + their pages/wiki and they don't seem to have logo pages or just one logo (EndeavourOS)

Mageia also doesn't seem to officially have a square logo https://wiki.mageia.org/en/Artwork_guidelines
Etc, so that process will take time.

For Pisi, this might work https://commons.wikimedia.org/wiki/File:Pisi_Linux_Logo.png

**Comment by razzeee** [comment]
Elementary people got back to me, I've amended this PR. So it should be good to go now.

**Comment by mwleeds** [comment]
EndeavorOS might be hard but for the ones that are just black I would think inverting them might be pretty easy in Inkscape.

**Comment by razzeee** [comment]
> EndeavorOS might be hard but for the ones that are just black I would think inverting them might be pretty easy in Inkscape.

correct, but I'm not sure if we would be violating style guides of the distros that way

**Comment by mwleeds** [comment]
I think it's hard to imagine people getting upset about a black to white change. I think distros would care if we were changing other colors.

**Comment by razzeee** [comment]
I can do those changes.

**Pull request merged**
