### PR TITLE
More specific information on claims of adherence to desktop standards (#191)

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
What needs to be done to move this forward?

**Comment by soc** [comment]
Is this good to go, or are there any other changes required for this PR?

**Comment by TingPing** [comment]
If you want to document `~/.var` better it should be another FAQ entry if anything, like *"Where does Flatpak store files"* or something. Flatpak'd applications are designed to respect the XDG env vars which is what that entry is about IMO.

**Comment by matthiasclasen** [comment]
Yes. Please make it a separate question. Flatpak does _not_ violate the base dir spec, it uses the (adherence of apps to the) spec to its advantage.

**Comment by soc** [comment]
@TingPing As mentioned, this is not about applications packaged with flatpak, this is about flatpak itself.

Flatpak indiscriminately dumps files into $HOME, thereby violating the spec, regardless of whether flatpak applications follow it.

@matthiasclasen I'm not sure how to explain it more clearly. Flatpak creates a directory inside $HOME, ignoring the xdg basedir spec. This is a clear violation of the spec, regardless of what flatpak applications do.

**Comment by matthiasclasen** [comment]
I think we'll have to agree to disagree.

**Pull request closed without merging**
