### PR TITLE
Update mint.svg

### PR DESCRIPTION
**Pull request by DartDeaDia**
New Linux Mint logo

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Thanks

**Comment by AsciiWolf** [comment]
Any chance you could also do a Pull Request for #591? :-)

**Comment by DartDeaDia** [comment]
> Any chance you could also do a Pull Request for #591? :-)

Ok

**Comment by AsciiWolf** [comment]
I did remove the comment because I was sadly not able to find an usable new Ubuntu logo. :-/

**Comment by haggen88** [comment]
@AsciiWolf @DartDeaDia  please consider a small dark border on the mint logo[ like this: [mint.svg.zip](https://github.com/flatpak/flatpak.github.io/files/11630150/mint.svg.zip) ], on a light theme the outer ring is lost and causes the proportions to change.

**Comment by AsciiWolf** [comment]
@haggen88 Feel free to send a PR. :-)

**Comment by haggen88** [comment]
> Feel free to send a PR. :-)

Ok

**Pull request merged**
