### PR TITLE
Update ubuntu.svg

### LINKED ISSUE #591: Update the Ubuntu logo
Ubuntu has a new logo since March 2022. It can be found here: https://design.ubuntu.com/resources

### PR DESCRIPTION
**Pull request by DartDeaDia**
Closes #591.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Thanks for the quick PR! This will however need more testing to find out whether the new logo does look good on the setup page.

**Comment by razzeee** [comment]
image

**Comment by DartDeaDia** [comment]
> image

Is it possible to adjust the icon size in the code?
Make it so that the vertical size would the same as other icons.

**Comment by AsciiWolf** [comment]
Probably good enough to be merged now. Let's merge it and we'll see.

**Pull request merged**
