### PR TITLE
distro: Remove information about Ubuntu GNOME Software plugin

### PR DESCRIPTION
**Pull request by AsciiWolf**
It is unsupported and not working properly since Ubuntu 20.04.

@smcv @allanday Please review and let me know whether it is fine to merge this. Thanks!

### CODE REVIEW

**Comment by smcv** [comment]
I am not an Ubuntu developer and cannot advise you on what they do and don't support.

**Comment by AsciiWolf** [comment]
Oops, I somehow thought that you were the one who co-maintain the official Ubuntu Flatpak PPA. Sorry!

**Comment by smcv** [comment]
> I somehow thought that you were the one who co-maintain the official Ubuntu Flatpak PPA

I do, but that doesn't mean I use Ubuntu myself, and certainly doesn't mean I'm an Ubuntu developer.

**Comment by AsciiWolf** [comment]
That's true, but you can still make a better review than someone who do not know anything about Ubuntu and its Flatpak support state. We probably won't get any review from Canonical and Ubuntu developers because they do not care about Flatpak.

**Comment by mwleeds** [comment]
Well, where did you find that it's not working properly? Just by trying it yourself? What issue did you run into?

**Comment by AsciiWolf** [comment]
@mwleeds See the current note at [Ubuntu setup](https://flatpak.org/setup/Ubuntu/) page:

> Note: the Software app is distributed as a Snap since Ubuntu 20.04 and does not support graphical installation of Flatpak apps. Installing the Flatpak plugin will also install a deb version of Software and result in two Software apps being installed at the same time.

Basically, installing `gnome-software-plugin-flatpak` on Ubuntu 20.04 and newer will install deb version of GNOME Software that will create conflicts (for example with the package filetype/url handling, updates checking, Shell search provider etc.) with the default Snap version. Having two GNOME Software installed and running at the same time is not a good idea at all.

**Comment by mwleeds** [comment]
So would it work to tell people to uninstall the Snap and use only the deb?

**Comment by AsciiWolf** [comment]
No, that would potentially broke the Ubuntu installation. The Snap version has all the changes/patches, fixes and branding needed for Ubuntu while the deb version, as far as I know, had those removed when Ubuntu switched to the Snap version and is now just a deb package synced from Debian with minimal changes.

**Comment by kenvandine** [comment]
I'd rather see this recommendation remain.  The only potential I see with having both installed is the URI handling.  Snap Store doesn't install a shell search provider.  Updates and package installations should not interfere in any way.

I have both installed on jammy and haven't run into any issues.

**Comment by AsciiWolf** [comment]
Thanks for your review, Ken! I personally ran into more issues when I tested it + have seen others having similar problems (I can try to find the relevant tickets), but it was some time ago. I will close this PR, however I would really love to see Ubuntu having a bit better Flatpak support for 22.04 so hacky solutions like this multiple Software centers one would not be needed anymore.

**Comment by AsciiWolf** [comment]
Regarding the "better support", see for example my ticket here: https://bugs.launchpad.net/snap-store-desktop/+bug/1950158

**Pull request closed without merging**
