### PR TITLE
Add dark mode

### LINKED ISSUE #446: Add dark theme
I can do it if you want.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

### PR DESCRIPTION
**Pull request by razzeee**
Closes https://github.com/flatpak/flatpak.github.io/issues/446

This is working fine as far as I can tell, however, there are two problems, that I'm aware of one we need to fix, we might be able to live with the other one.

1. Landingscreen image still has white in it
2. Distro page has some black logos on a now black background, they are still visible, but it's not ideal

Not happy, that I had to use that many `!important`, but I don't think it will matter in the long run and might be the best we can do with bootstrap 3?

I tried to be throughout and checked every page in both light and dark again, they seem fine, but I'm not sure if there are any hidden pages.

image

image

image

image

image

image

### CODE REVIEW

**Comment by A6GibKm** [comment]
Is it possible to load different assets for the 5 low contrast distros?

**Comment by razzeee** [comment]
Probably, I'm not very familiar with ruby.

Other solutions:
1. Use a color that works on both backgrounds
2. Use responsive SVG (doesn't work in WebKit)

The other problem is, that distros might not like us to use colors they never intended to be used, might even be true for black/white versions.

**Comment by TingPing** [comment]
Could you put a white background behind them?

**Comment by A6GibKm** [comment]
I feel the only distro with low contrast here that cant be color swapped is void's, they have a logo without letters I think?

**Comment by razzeee** [comment]
image

**Review by mwleeds — APPROVED** [review]
These changes look pretty reasonable. It doesn't seem like something that needs meticulous review. We can always make the distro page prettier as follow-up work.

**Pull request merged**
