### PR TITLE
Add instructions for elementary and Pop! themes

### PR DESCRIPTION
**Pull request by cassidyjames**
This makes Flatpaks integrate with the OS a lot better if users have the system default settings.

### CODE REVIEW

**Comment by TingPing** [comment]
For what its worth this should never be needed. First call to `flatpak install` or `flatpak update` will automatically install the Gtk theme.

**Comment by cassidyjames** [comment]
That hasn't been my (or our users) experience; how does it find the appropriate GTK theme? Is this a recent change or update? It's possible we're hitting a different bug, but this is how we currently encourage users to use Flatpak.

**Comment by TingPing** [comment]
> how does it find the appropriate GTK theme?

It queries gsettings (`gsettings get org.gnome.desktop.interface gtk-theme` to test).

>  Is this a recent change or update?

Added in `0.10.1` last year. All distros should be using `0.10` at least if they want a well supported version.

**Comment by cassidyjames** [comment]
Strange. If this is not necessary, I'll close it out and keep a closer eye on the reports of unthemed apps.

**Pull request closed without merging**
