### PR TITLE
update Solus rows

### PR DESCRIPTION
**Pull request by Drsheppard01**
1. No need install flatpak package (pre-installed)
2. Need sudo for adding repo

### CODE REVIEW

**Comment by AsciiWolf** [comment]
ad 1. Why isn't _xdg-desktop-portal-gtk_ (or _xdg-desktop-portal-kde_ in case of Solus Plasma) preinstalled on Solus if _flatpak_ is? Shouldn't this be reported as a bug report to Solus devs?
ad 2. Why using sudo to add the repo? Polkit is not working on Solus? By the way, is there any way to add the repo using GUI (Software Center) on Solus?

**Comment by Drsheppard01** [comment]
> ad 1. Why isn't _xdg-desktop-portal-gtk_ (or _xdg-desktop-portal-kde_ in case of Solus Plasma) preinstalled on Solus if _flatpak_ is? Shouldn't this be reported as a bug report to Solus devs?
> ad 2. Why using sudo to add the repo? Polkit is not working on Solus? By the way, is there any way to add the repo using GUI (Software Center) on Solus?

1. IDK, better asked from developers, but I'm not sure if it looks like a bug
2. mkdirat: access denied

**Comment by AsciiWolf** [comment]
To be honest, both of your points look like Solus bugs to me.

**Comment by AsciiWolf** [comment]
Is the issue still present on Solus?

**Comment by Drsheppard01** [comment]
Yes

**Comment by AsciiWolf** [comment]
It really needs to be discussed with Solus devs instead of adding workarounds for their broken Polkit/Flatpak support.

**Comment by Staudey** [comment]
Just to chime in here

1. That issue should be solved on Solus' end, right.
2. The sudo is not necessary at least on Solus Budgie; @Drsheppard01 if this really still happens to you, you should report it on the Solus dev tracker.

**Comment by AsciiWolf** [comment]
Thanks for your comment! I will close this PR. It really should be fixed in Solus instead.

**Pull request closed without merging**
