### PR TITLE
Don't use https uris for the remote

### PR DESCRIPTION
**Pull request by alexlarsson**
This is super slow, and we don't neeed the encryption anyway, since
the actual data is gpg signed.

### CODE REVIEW

**Comment by bochecha** [comment]
> This is super slow

Is it really much slower?

> we don't neeed the encryption anyway, since the actual data is gpg signed.

HTTPS doesn't just allow the client to verify that they download the right thing (which GPG signatures also accomplish as you mention), it also hides the URLs requested by the client (for example, the fact that they installed Telegram to chat privately).

**Comment by alexlarsson** [comment]
I did some quick testing, and its not hugely slow for me atm. A few seconds for downloading the gnome runtime (160 meg). However, at times i've seen sdk.gnome.org be very slow, and I suspect SSL may be part of the issue. I mean, encrypting 160 meg of data for each user is hardly cheap.

I guess we need some more research on this.

**Comment by alexlarsson** [comment]
(a few seconds more for https that is, that is not the total time)

**Comment by alexlarsson** [comment]
Oh, it seems http is redirected to https anyway, which definately makes this change inefficient atm.

**Pull request merged**
