### PR TITLE
Setup on NixOS: Use option services.flatpak.enable

### LINKED ISSUE #324: NixOS setup instructions don't work: "The name org.freedesktop.Flatpak.SystemHelper was not provided by any .service files" when trying to install app
After following the setup instructions for NixOS, application installation through flatpak doesn't work and aborts with "The name org.freedesktop.Flatpak.SystemHelper was not provided by any .service files"

## To reproduce

On a NixOS system without flatpak installed yet,

1. follow the [setup instructions](https://flatpak.org/setup/NixOS/):
   * `sudo nix-env -iA nixos.flatpak`
   *  `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
   * restart the system
2. then, try to install some application: `flatpak install flathub org.videolan.VLC`
   * When prompted "Do you want to install it?", enter `y` <kbd>Enter</kbd>
   * When prompted "Is this ok", enter `y` <kbd>Enter</kbd>

(Whether or not you actually reboot between the setup and trying to install an application doesn't seem to matter.)

### Expected

Application (here: VLC) gets installed and can be used (here, with `flatpak run org.videolan.VLC`)

### Observed

```
Required runtime for org.videolan.VLC/x86_64/stable (runtime/org.kde.Platform/x86_64/5.12) found in remote flathub
Do you want to install it? [y/n]: y
Installing in system:
org.kde.Platform/x86_64/5.12                       flathub 390117f85e94
org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08  flathub 4a30b71b2e21
org.freedesktop.Platform.html5-codecs/x86_64/18.08 flathub 71faea5b07a6
org.kde.KStyle.Adwaita/x86_64/5.12                 flathub ff24e32a3ab8
org.kde.Platform.Locale/x86_64/5.12                flathub 7ffc988cf203
org.videolan.VLC/x86_64/stable                     flathub fed20a3d9529
  permissions: ipc, network, pulseaudio, x11, devices
  file access: host, xdg-config/kdeglobals:ro, xdg-run/dconf, ~/.config/dconf:ro
  dbus access: ca.desrt.dconf, com.canonical.AppMenu.Registrar, com.canonical.AppMenu.Registrar.*, org.freedesktop.ScreenSaver, org.freedesktop.secrets, org.kde.kwalletd, org.kde.kwalletd5, org.mpris.MediaPlayer2.Player
  dbus ownership: org.mpris.MediaPlayer2.vlc
org.videolan.VLC.Locale/x86_64/stable              flathub 34eac0f7c343
Is this ok [y/n]: y
Installing: org.kde.Platform/x86_64/5.12 from flathub
[####################] 1 metadata, 0 content objects fetched; 569 B transferred in 0 seconds
error: Failed to install org.kde.Platform/x86_64/5.12: The name org.freedesktop.Flatpak.SystemHelper was not provided by any .service files
```

## Workaround / fix

1. Set [NixOS option `services.flatpak.enable`](https://nixos.org/nixos/options.html#services.flatpak.enable) to `true`, e.g. by having
    ```nix{ config, lib, pkgs, ... }:
    { config, lib, pkgs, ... }:
    {
      # ...
    
      services.flatpak.enable = true;
    
      # ...
    }
    ```
    in `/etc/nixos/configuration.nix`
2. Rebuild and then either boot into or switch into the new configuration, e.g. with `sudo nixos-rebuild switch`

This will actually also pull in the [`nixpkgs.flatpak` derivation](https://nixos.org/nixos/packages.html#flatpak), so `sudo nix-env -iA nixos.flatpak` isn't required.

---

Output of `nix-shell -p nix-info --run "nix-info -m"`:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.105, NixOS, 18.09.2327.37694c8cc0e (Jellyfish)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.1.3`
 - channels(root): `"nixos-18.09.2327.37694c8cc0e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### PR DESCRIPTION
**Pull request by das-g**
fixes #324

### CODE REVIEW

**Comment by das-g** [comment]
Can you have a look at this, @allanday? The currently documented approach doesn't work. (See #324.)

**Comment by tbenst** [comment]
bump! The corrected instructions work for me, but original do not

**Comment by allanday** [comment]
Really sorry for the slow response.

I can't vouch for their technical validity, but the changes seem well-written.

**Comment by das-g** [comment]
When will https://flatpak.org/setup/NixOS/ reflect this change? Is there some sort of release process?

**Comment by das-g** [comment]
> I can't vouch for their technical validity, but the changes seem well-written.

Well, Graham did vouch from them with his review. That's almost as good as an official NixOS seal of approval, I think. :wink:

**Comment by allanday** [comment]
> When will https://flatpak.org/setup/NixOS/ reflect this change? Is there some sort of release process?

The website needs to be updated with the changes - should happen later today.



> Well, Graham did vouch from them with his review. That's almost as good as an official NixOS seal of approval, I think

Heh, OK. :smile:

**Pull request merged**
